add `min_by_key` and `max_by_key`
fosskers/nonempty-collections pull request #11
Opened 2024-02-28 15:36 UTC by rinde

Hello, I noticed that these two functions were missing (when comparing with `Iterator` in `std`). Let me know if you have any comments.

2024-02-28 23:52 UTC, fosskers approved these changes
Thanks for this!

Just a few minor nits.

2024-02-28 23:52 UTC, fosskers commented on src/iter.rs
> +    /// let max = nev!["hi", "hey", "rust", "yolo"].into_nonempty_iter().max_by_key(|item|item.len());
```suggestion
    /// let max = nev!["hi", "hey", "rust", "yolo"].into_nonempty_iter().max_by_key(|item| item.len());
```

2024-02-28 23:52 UTC, fosskers commented on src/iter.rs
> +    fn max_by_key<B: Ord, F>(self, mut key: F) -> Self::Item
Let's put the `Ord` constraint in the `where` clause.

2024-02-28 23:52 UTC, fosskers commented on src/iter.rs
> +    /// let min = nev!["hi", "hello", "greetings", "hy"].into_nonempty_iter().min_by_key(|item|item.len());
```suggestion
    /// let min = nev!["hi", "hello", "greetings", "hy"].into_nonempty_iter().min_by_key(|item| item.len());
```

2024-02-28 23:52 UTC, fosskers commented on src/iter.rs
> +    fn min_by_key<B: Ord, F>(self, mut key: F) -> Self::Item
Here too.

2024-02-28 23:53 UTC, fosskers requested changes
Accidentally approved too quickly.

2024-02-29 13:30 UTC, rinde commented
@fosskers Thanks for the feedback! I updated the code.

2024-03-01 00:20 UTC, merged

2024-03-01 00:20 UTC, fosskers commented
Thanks again!