Implement `Result<T,E>` collection for non-empty iterator
fosskers/nonempty-collections pull request #3
Opened 2023-08-17 19:33 UTC by gshuflin

This PR implements `FromNonEmptyIterator` for `Result<T,E>`, so that non-empty iterators of `Result` types can use the `.collect::<Result<NEVec<_>, Error>>()` idiom to create a single `Result` containing a nonempty collection in its `Ok` branch.

2023-08-18 00:12 UTC, fosskers commented
Ah I saw your other PR first and was confused. Alright I'll look over this one first!

2023-08-22 16:26 UTC, gshuflin commented
> Ah I saw your other PR first and was confused. Alright I'll look over this one first!

Thanks for taking a look! It looks like the CI pipeline is failing with a spurious network error at the moment.

2023-08-23 00:50 UTC, fosskers commented
There are some funky issues with `serde` at the moment. Let's run it again.

2023-08-24 08:01 UTC, fosskers requested changes

2023-09-05 01:26 UTC, merged

2023-09-05 01:26 UTC, fosskers commented
I just published `0.1.2`. Thanks for this!